# Generated by Django 4.2.11 on 2024-03-25 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
