# Generated by Django 4.1.13 on 2024-04-07 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
    ]
