# Generated by Django 4.1.13 on 2024-04-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mode',
            field=models.CharField(default='light', max_length=10),
        ),
    ]
