# Generated by Django 4.1.13 on 2024-04-15 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_userprofile_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mode',
        ),
    ]
