# Generated by Django 4.1.13 on 2024-04-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='total_spendings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
